insert into authors (id, first_name, last_name) values (1, 'Ursulina', 'Thorsby');
insert into authors (id, first_name, last_name) values (2, 'Levy', 'McWilliams');
insert into authors (id, first_name, last_name) values (3, 'Chiquia', 'Klishin');
insert into authors (id, first_name, last_name) values (4, 'Lammond', 'Tyer');
insert into authors (id, first_name, last_name) values (5, 'Hank', 'Giacopini');
insert into authors (id, first_name, last_name) values (6, 'Joline', 'Griffin');
insert into authors (id, first_name, last_name) values (7, 'Edyth', 'Hutchins');
insert into authors (id, first_name, last_name) values (8, 'Jemie', 'Fritchley');
insert into authors (id, first_name, last_name) values (9, 'Bertha', 'Brownhill');
insert into authors (id, first_name, last_name) values (10, 'Misti', 'Brownscombe');
insert into authors (id, first_name, last_name) values (11, 'Kent', 'Collinson');
insert into authors (id, first_name, last_name) values (12, 'Cedric', 'Adolf');
insert into authors (id, first_name, last_name) values (13, 'Langsdon', 'Allred');
insert into authors (id, first_name, last_name) values (14, 'Danni', 'Plak');
insert into authors (id, first_name, last_name) values (15, 'Dorian', 'Braiden');
insert into authors (id, first_name, last_name) values (16, 'Brodie', 'Nowaczyk');
insert into authors (id, first_name, last_name) values (17, 'Aila', 'Robjant');
insert into authors (id, first_name, last_name) values (18, 'Chloris', 'Lacroix');
insert into authors (id, first_name, last_name) values (19, 'Kaitlyn', 'Ribchester');
insert into authors (id, first_name, last_name) values (20, 'Jennie', 'Foad');
insert into authors (id, first_name, last_name) values (21, 'Hedwig', 'Anderl');


insert into books (id, price, price_old, title, author_id) values (1, 1851, 1142, 'Keylex', 1);
insert into books (id, price, price_old, title, author_id) values (2, 1920, 3090, 'Stronghold', 2);
insert into books (id, price, price_old, title, author_id) values (3, 1166, 2765, 'Regrant', 3);
insert into books (id, price, price_old, title, author_id) values (4, 1915, 3040, 'Bigtax', 4);
insert into books (id, price, price_old, title, author_id) values (5, 825, 3200, 'Regrant', 5);
insert into books (id, price, price_old, title, author_id) values (6, 2776, 2014, 'Zontrax', 6);
insert into books (id, price, price_old, title, author_id) values (7, 1128, 1210, 'Andalax', 7);
insert into books (id, price, price_old, title, author_id) values (8, 2078, 1163, 'Wrapsafe', 8);
insert into books (id, price, price_old, title, author_id) values (9, 2489, 1818, 'Gembucket', 9);
insert into books (id, price, price_old, title, author_id) values (10, 689, 3822, 'Home Ing', 10);
insert into books (id, price, price_old, title, author_id) values (11, 1737, 1100, 'Domainer', 1);
insert into books (id, price, price_old, title, author_id) values (12, 723, 2635, 'Kanlam', 12);
insert into books (id, price, price_old, title, author_id) values (13, 2297, 2745, 'Y-Solowarm', 13);
insert into books (id, price, price_old, title, author_id) values (14, 1671, 1837, 'Konklux', 14);
insert into books (id, price, price_old, title, author_id) values (15, 1770, 1371, 'Cardify', 15);
insert into books (id, price, price_old, title, author_id) values (16, 748, 2427, 'Latlux', 16);
insert into books (id, price, price_old, title, author_id) values (17, 783, 3906, 'Opela', 17);
insert into books (id, price, price_old, title, author_id) values (18, 2400, 1166, 'Tres-Zap', 18);
insert into books (id, price, price_old, title, author_id) values (19, 1390, 2706, 'Greenlam', 19);
insert into books (id, price, price_old, title, author_id) values (20, 1061, 1723, 'Bitchip', 20);
insert into books (id, price, price_old, title, author_id) values (21, 904, 3267, 'Biodex', 21);
